if(NOT DEFINED SCALAPACK_COMPONENTS AND DEFINED ENV{MKLROOT})
  set(SCALAPACK_COMPONENTS MKL)
endif()

if(MKL IN_LIST SCALAPACK_COMPONENTS)
  if(intsize64)
    list(APPEND SCALAPACK_COMPONENTS MKL64)
  endif()
endif()

find_package(SCALAPACK REQUIRED COMPONENTS ${SCALAPACK_COMPONENTS})
