name: ci

env:
  HOMEBREW_NO_INSTALL_CLEANUP: 1

on:
  push:
    paths:
      - "**.c"
      - "**.f"
      - "**.F"
      - "**.f90"
      - "**.F90"
      - "**.cmake"
      - "**.cmake.in"
      - "**.txt"
      - "cmake/libraries.json"
      - ".github/workflows/ci.yml"
      - "!scripts/*"

  workflow_dispatch:

# avoid wasted runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  core:
    timeout-minutes: 15

    strategy:
      matrix:
        parallel: [true]
        mpich: [false]
        lapack_vendor: [""]
        os: [ubuntu-latest, macos-latest]
        include:
          - lapack_vendor: "OpenBLAS"
            parallel: true
            os: ubuntu-latest
            name: OpenBLAS
          - parallel: false
            os: ubuntu-latest
          - mpich: true
            parallel: true
            os: ubuntu-latest
            name: MPICH

    name: ${{ matrix.os }}-parallel=${{ matrix.parallel }}-${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    steps:

    - &checkout
      uses: actions/checkout@v6

    - &prereqs
      name: install prereqs
      uses: ./.github/workflows/composite-deps

    - &macos_fortran
      name: set Fortran compiler FC (macOS)
      if: runner.os == 'macOS'
      run: echo "FC=gfortran-15" >> $GITHUB_ENV

    - name: build and install
      uses: ./.github/workflows/composite-build

    - name: build example
      uses: ./.github/workflows/composite-example


  gnu-make:
    # this is important case as due to project complexity, some failures only happen with GNU Make (or Ninja)
    timeout-minutes: 15

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - *checkout
    - *prereqs
    - *macos_fortran

    - name: build and test with GNU Make
      shell: bash
      run: cmake --workflow gmake


  shared:
    timeout-minutes: 15
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - *checkout
    - *prereqs
    - *macos_fortran

    - run: cmake --workflow shared
    - run: cmake --install build-shared

    - name: example workflow
      working-directory: example
      run: cmake --workflow shared

  openmp:
    timeout-minutes: 15
    strategy:
      matrix:
        preset: [openmp-nompi, openmp-mpi]

    runs-on: ubuntu-latest

    steps:
    - *checkout
    - *prereqs

    - run: cmake --workflow ${{ matrix.preset }}

    - run: cmake --install build

    - name: example workflow
      working-directory: example/openmp
      run: cmake --workflow ${{ matrix.preset }}


  scotch:
    timeout-minutes: 15

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        scotch: [true]

    runs-on: ${{ matrix.os }}

    steps:
    - *checkout
    - *prereqs
    - *macos_fortran

    - name: Load Homebrew environment (macOS)
      if: runner.os == 'macOS'
      run: |
        eval "$(/opt/homebrew/bin/brew shellenv)"
        printenv >> $GITHUB_ENV
# necessary to find Homebrew Bison to build Scotch on macOS

    - run: cmake --workflow scotch
    - run: cmake --install build-scotch

    - name: example workflow
      working-directory: example/scotch
      run: cmake --workflow scotch


  metis:
    timeout-minutes: 15
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - *checkout
    - *prereqs
    - *macos_fortran

    - run: cmake --workflow metis
    - run: cmake --install build-metis

    - name: example workflow
      working-directory: example/metis
      run: cmake --workflow metis


  parmetis:
    timeout-minutes: 15
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - *checkout
    - *prereqs
    - *macos_fortran

    - run: cmake --workflow parmetis
    - run: cmake --install build-parmetis

    - name: example workflow
      working-directory: example/metis
      run: cmake --workflow parmetis
      # parmetis also uses example/metis


  cmake-older:
    timeout-minutes: 30

    runs-on: ubuntu-latest

    strategy:
      matrix:
        cmake_version: ["3.25.3"]

    steps:
    - *checkout
    - *prereqs

    - uses: ./.github/workflows/composite-cmake

    - name: configure
      run: $CMAKE --workflow --preset default
# syntax needed for older CMake

    - name: install package
      run: $CMAKE --install build


# test this project used as an archive in other projects
  archive:
    timeout-minutes: 15

    runs-on: ubuntu-latest

    steps:
    - *checkout
    - *prereqs

    - name: Test Project as archive
      run: cmake -S example/other_project -B build

# if broken, the CMake configure step fails
