name: ci_build

env:
  CTEST_NO_TESTS_ACTION: error
  CMAKE_BUILD_PARALLEL_LEVEL: 4
  CTEST_PARALLEL_LEVEL: 0
  CMAKE_INSTALL_PREFIX: ~/libs
  CMAKE_PREFIX_PATH: ~/libs

on:
  push:
    paths:
      - "scripts/CMakeLists.txt"
      - ".github/workflows/ci_build.yml"

jobs:

  linux:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Install prereqs (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt update
        sudo apt install --no-install-recommends libopenmpi-dev openmpi-bin liblapack-dev

    - name: Install prereqs (macOS)
      if: runner.os == 'macOS'
      run: |
        brew install flang open-mpi
        echo "FC=flang" >> $GITHUB_ENV

    - name: configure
      run: cmake --preset default

    - name: build, test release
      run: cmake --workflow --preset default

    - run: cmake --install build

# builds fine on local machine
    # - name: configure example
    #   run: cmake -S example -B example/build -DBUILD_SHARED_LIBS:BOOL=${{ matrix.shared }}
    # - name: build example
    #   run: cmake --build example/build
    # - name: test example
    #   run: ctest --test-dir example/build -V
