name: ci_windows

on:
  push:
    paths:
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/ci_windows.yml"
      - "!scripts/*"
  workflow_dispatch:

# avoid wasted runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  windows:
    runs-on: windows-latest
    timeout-minutes: 15

    steps:
    - uses: msys2/setup-msys2@v2
      id: msys2
      with:
        update: true
        install: >-
          mingw-w64-ucrt-x86_64-gcc-fortran
          mingw-w64-ucrt-x86_64-lapack

    - name: Put MSYS2_MinGW64 on PATH
      run: echo "${{ steps.msys2.outputs.msys2-location }}/ucrt64/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - &checkout
      uses: actions/checkout@v6

    - name: build & test no-MPI
      run: cmake --workflow nompi
      env: &lapack
        LAPACK_ROOT: ${{ steps.msys2.outputs.msys2-location }}/ucrt64

    - name: install package
      run: cmake --install build

    - name: example workflow
      working-directory: example
      run: cmake --workflow nompi
      env: *lapack

    - name: Upload log failure
      if: failure()
      uses: actions/upload-artifact@v7
      with:
        name: example-${{ runner.os }}-CMakeConfigureLog.yaml
        path: example/build/CMakeFiles/CMakeConfigureLog.yaml

# works, just saving CI resources

  # wsl:
  #   runs-on: windows-latest
  #   timeout-minutes: 10

  #   defaults:
  #     run:
  #       shell: wsl-bash {0}

  #   steps:

  #   - uses: Vampire/setup-wsl@v7
  #     with:
  #       distribution: Ubuntu-24.04
  #       additional-packages:
  #         cmake ninja-build gcc g++ gfortran liblapack-dev libscalapack-openmpi-dev libopenmpi-dev
  #       use-cache: true
  #       wsl-shell-user: tester

  #   - name: tell OS release
  #     run: cat /etc/os-release

  #   - name: tell WSL version
  #     run: wsl.exe -l -v
  #     shell: pwsh

  #   - *checkout

  #   - name: CMake workflow
  #     run: cmake --workflow --preset linux

  #   - name: CMake install
  #     run: cmake --install /tmp/build

  #   - name: Upload log failure
  #     if: failure()
  #     uses: actions/upload-artifact@v7
  #     with:
  #       archive: false
  #       name: example-${{ runner.os }}-CMakeConfigureLog.yaml
  #       path: /tmp/build-ex/CMakeFiles/CMakeConfigureLog.yaml
